apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-pdy
  labels:
       app: pdy
       tier: bd
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"


