apiVersion: v1
kind: PersistentVolume
metadata:
  name: pdy-pv-volume
  labels:
      app: pdy
      tier: frontend
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/pdy/"


