apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdy-pvc
  namespace: paymybuddy
  labels:
          app: pdy
          tier: frontend
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M

