apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-pdy
  namespace: paymybuddy
  labels:
          app: pdy
          tier: bd
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M

